# permissions for end users to edit resourceoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourceoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-operator-k8s
    app.kubernetes.io/part-of: demo-operator-k8s
    app.kubernetes.io/managed-by: kustomize
  name: resourceoperator-editor-role
rules:
- apiGroups:
  - test-operator.deriv.services
  resources:
  - resourceoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test-operator.deriv.services
  resources:
  - resourceoperators/status
  verbs:
  - get
