---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test-operator.deriv.services
  resources:
  - resourceoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test-operator.deriv.services
  resources:
  - resourceoperators/finalizers
  verbs:
  - update
- apiGroups:
  - test-operator.deriv.services
  resources:
  - resourceoperators/status
  verbs:
  - get
  - patch
  - update
